[WEBSITE-959] Allow multiple urls in the template document
ukparliament/parliament-opensearch pull request #7
Opened 2017-05-09 12:19 UTC by katylouise

* Changed implementation to store different template urls and types from the description, replacing the single @base_url.
* Updated documentation.
* Fixed some of the rubocop violations.

2017-05-09 12:49 UTC, mattrayner approved these changes

2017-05-09 12:49 UTC, mattrayner commented on lib/parliament/request/open_search_request.rb
> +        type ||= 'application/atom+xml'
should this not just be `type = 'application/atom+xml'` in the parameters above?

2017-05-09 12:50 UTC, mattrayner requested changes
see above

2017-05-11 12:36 UTC, mattrayner requested changes
Have we tested the scenario where there is no description URL with a provided type in the description file?

I.e. I want type application/json but there isn't one available

2017-05-11 12:36 UTC, mattrayner commented on lib/parliament/request/open_search_request.rb
> +        url_hash = @templates[:url].select { |url| url[:type] == type }.first
What if this is nil?

2017-05-11 12:59 UTC, katylouise commented on lib/parliament/request/open_search_request.rb
> +        url_hash = @templates[:url].select { |url| url[:type] == type }.first
good point, I'll add testing around this

2017-05-15 11:54 UTC, mattrayner requested changes

2017-05-15 11:54 UTC, mattrayner commented on lib/parliament/builder/open_search_response_builder.rb
> +      OPEN_SEARCH_ELEMENTS = %w[totalResults Query startIndex itemsPerPage].freeze
should these be changed back?

2017-05-15 11:54 UTC, mattrayner commented on spec/spec_helper.rb
> +  config.filter_sensitive_data('<AUTH_TOKEN>') { ENV['OPENSEARCH_AUTH_TOKEN'] }
We should also filter the API url

2017-05-15 11:54 UTC, mattrayner commented on spec/spec_helper.rb
> +  config.filter_sensitive_data('<AUTH_TOKEN>') { ENV['OPENSEARCH_AUTH_TOKEN'] }
See prototype for implementation

2017-05-15 11:54 UTC, mattrayner commented on spec/spec_helper.rb
> +
needed?

2017-05-15 12:02 UTC, katylouise commented on spec/spec_helper.rb
> +  config.filter_sensitive_data('<AUTH_TOKEN>') { ENV['OPENSEARCH_AUTH_TOKEN'] }
done

2017-05-17 09:57 UTC, mattrayner approved these changes

2017-05-17 09:57 UTC, merged